# Generated by Django 3.1.3 on 2021-05-20 06:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ChatAPI', '0002_auto_20210520_1134'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomResponses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=1000, verbose_name='title')),
                ('responses', models.TextField()),
                ('user', models.ForeignKey(default='Guest', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
